name: Audiodragon Push Action
run-name: Push Action for ${{ github.sha }} on ${{ github.ref_name }}
on: [push]
jobs:
  Test Changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: java -version
      - run: cd ${{ github.workspace }}
      - run: ./gradlew test
