name: Audiodragon Release Pipeline
run-name: Release ${{ github.ref_name }}
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: java -version
      - run: cd ${{ github.workspace }}
      - run: ./gradlew test
  create-release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd ${{ github.workspace }}
      - run: ./build.sh
      - run: |
          PROJECT_NAME=$(./gradlew properties -q | grep "^name:" | awk '{print $2}')
          PROJECT_VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          cp build/libs/$PROJECT_NAME-$PROJECT_VERSION.jar audiodragon-${{ github.ref_name }}.jar
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false
      - name: Upload Release Artifact
        id: upload-release-artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./audiodragon-${{ github.ref_name }}.jar
          asset_name: audiodragon-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive