name: Audiodragon Snapshot Action
run-name: Push Action for ${{ github.sha }} on ${{ github.ref_name }}
on:
  push:
    branches:
      - actions # FIXME
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd ${{ github.workspace }}
      - run: ./build.sh
